assigmnent_2
GOEgor/python_basic_programming pull request #1
Opened 2020-03-15 10:59 UTC by GOEgor

Simple solution with sneaker sales site parsing

2020-03-16 14:54 UTC, SpirinEgor requested changes

2020-03-16 14:54 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +            return
Это не совсем правильная проверка, всё-таки хочется вставлять кроссовки, которых ещё нет.
Используй `INSERT or REPLACE`, например

2020-03-16 14:54 UTC, SpirinEgor commented on assignment_2/client/data_worker.js
> +                if (key == "old_price") {
в `js` сравнение лучше делать через `===`
```
3 == "3" // true
```

2020-03-16 14:54 UTC, SpirinEgor commented on assignment_2/client/data_worker.js
> +                    new_val = '<strike>' + val + '</strike>';
`<strike>` deprecated
используй `<del>`

2020-03-16 20:44 UTC, GOEgor commented on assignment_2/server/app_db.py
> +            return
`INSERT or REPLACE` не работает с id, который у меня автоматически инкрементировался, пришлось вручную этот id добавлять в базу данных

2020-03-17 14:24 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +    for product in products:
```
for product, product_index in enumerate(products):
```
и тогда не надо будет инкрементировать в конце

2020-03-17 14:24 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +            return
Да, логика верная, но подход немного неправильный, если порядок выдачи на сайте поменяется, то у тебя всё сломается. Надо либо брать какой-то артикул за id, либо название в крайнем случае

2020-03-17 14:29 UTC, SpirinEgor reviewed
Откомментил, что лучше в качестве id использовать не собственный id, а что-то уникальное для каждого предмета, например, в твоём случае, для каждого товара есть следующий блок:
```
<div class="iproduct__title">
    <a href="/ru/men/products/4192/7440">Converse One Star Ox</a>
</div>
```
вот `7440` или `41927440` можно использовать в качестве `id`

2020-03-17 14:29 UTC, SpirinEgor commented on assignment_2/server/app_db.py
>  from flask import Flask, g, request
`request` не используется.

2020-03-22 21:58 UTC, GOEgor commented
@SpirinEgor :done:

2020-03-24 18:20 UTC, SpirinEgor requested changes
Что-то не работает. Запустил всё, а кроссовки не отображаются, с сервера пустой массив возвращается

2020-03-24 18:20 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +            db.commit()
Коммит надо делать всего один, после цикла

2020-03-24 18:20 UTC, SpirinEgor commented on assignment_2/server/app_db.py
> +        data = extract_data()
Часть с загрузкой данных лучше вынести из инициализации, так как одно проверяет наличие необходимых страниц, а другое наполняет контентом. Ну и случай из соседнего пр: если сайт недоступен, то инициализация падает и всё приложение не работает, хотя всё могло бы работать просто без части данных.

2020-04-16 17:15 UTC, GOEgor commented
@SpirinEgor не работало, потому что тот сайт, что я парсил изначально (sneaker.sale) при поиске сначала выдавал что-то типо "Ничего не нашлось", а потом подгружал результаты поиска. В итоге requests.get получал страницу, где ничего не нашлось. Пробовал разные способы подгрузить, но ничего не сработало( Поэтому я так долго и не исправлял, не хотелось другой сайт искать.

В итоге, конечно, распарсил другой сайт, и все должно быть норм. 😃

2020-04-20 09:18 UTC, SpirinEgor approved these changes

2020-04-20 13:18 UTC, merged